// <auto-generated />
using System;
using FurnitureShop.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FurnitureShop.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622120519_Phase2_Inventory")]
    partial class Phase2_Inventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FurnitureShop.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("[Slug] IS NOT NULL");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nội thất phòng khách sang trọng",
                            DisplayOrder = 1,
                            ImageUrl = "/images/categories/phong-khach.jpg",
                            IsActive = true,
                            Name = "Phòng Khách",
                            Slug = "phong-khach"
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nội thất phòng ngủ êm ái",
                            DisplayOrder = 2,
                            ImageUrl = "/images/categories/phong-ngu.jpg",
                            IsActive = true,
                            Name = "Phòng Ngủ",
                            Slug = "phong-ngu"
                        },
                        new
                        {
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nội thất phòng ăn tinh tế",
                            DisplayOrder = 3,
                            ImageUrl = "/images/categories/phong-an.jpg",
                            IsActive = true,
                            Name = "Phòng Ăn",
                            Slug = "phong-an"
                        },
                        new
                        {
                            CategoryId = 10,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nội thất văn phòng tại nhà",
                            DisplayOrder = 4,
                            ImageUrl = "/images/categories/phong-lam-viec.jpg",
                            IsActive = true,
                            Name = "Phòng Làm Việc",
                            Slug = "phong-lam-viec"
                        },
                        new
                        {
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sofa các loại",
                            DisplayOrder = 1,
                            ImageUrl = "/images/categories/sofa.jpg",
                            IsActive = true,
                            Name = "Sofa",
                            ParentId = 1,
                            Slug = "sofa"
                        },
                        new
                        {
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bàn nước, bàn trà",
                            DisplayOrder = 2,
                            ImageUrl = "/images/categories/ban-tra.jpg",
                            IsActive = true,
                            Name = "Bàn Trà",
                            ParentId = 1,
                            Slug = "ban-tra"
                        },
                        new
                        {
                            CategoryId = 11,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ghế đọc sách, ghế nghỉ",
                            DisplayOrder = 3,
                            ImageUrl = "/images/categories/ghe-thu-gian.jpg",
                            IsActive = true,
                            Name = "Ghế Thư Giãn",
                            ParentId = 1,
                            Slug = "ghe-thu-gian"
                        },
                        new
                        {
                            CategoryId = 12,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kệ tivi, tủ tivi",
                            DisplayOrder = 4,
                            ImageUrl = "/images/categories/tu-tivi.jpg",
                            IsActive = true,
                            Name = "Tủ Tivi",
                            ParentId = 1,
                            Slug = "tu-tivi"
                        },
                        new
                        {
                            CategoryId = 13,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kệ sách, kệ trang trí",
                            DisplayOrder = 5,
                            ImageUrl = "/images/categories/ke-trang-tri.jpg",
                            IsActive = true,
                            Name = "Kệ Trang Trí",
                            ParentId = 1,
                            Slug = "ke-trang-tri"
                        },
                        new
                        {
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giường ngủ các loại",
                            DisplayOrder = 1,
                            ImageUrl = "/images/categories/giuong.jpg",
                            IsActive = true,
                            Name = "Giường",
                            ParentId = 2,
                            Slug = "giuong"
                        },
                        new
                        {
                            CategoryId = 7,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tủ đựng quần áo",
                            DisplayOrder = 2,
                            ImageUrl = "/images/categories/tu-quan-ao.jpg",
                            IsActive = true,
                            Name = "Tủ Quần Áo",
                            ParentId = 2,
                            Slug = "tu-quan-ao"
                        },
                        new
                        {
                            CategoryId = 14,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bàn phấn, gương",
                            DisplayOrder = 3,
                            ImageUrl = "/images/categories/ban-trang-diem.jpg",
                            IsActive = true,
                            Name = "Bàn Trang Điểm",
                            ParentId = 2,
                            Slug = "ban-trang-diem"
                        },
                        new
                        {
                            CategoryId = 15,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tab đầu giường",
                            DisplayOrder = 4,
                            ImageUrl = "/images/categories/tu-dau-giuong.jpg",
                            IsActive = true,
                            Name = "Tủ Đầu Giường",
                            ParentId = 2,
                            Slug = "tu-dau-giuong"
                        },
                        new
                        {
                            CategoryId = 16,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bàn ăn các loại",
                            DisplayOrder = 1,
                            ImageUrl = "/images/categories/ban-an.jpg",
                            IsActive = true,
                            Name = "Bàn Ăn",
                            ParentId = 3,
                            Slug = "ban-an"
                        },
                        new
                        {
                            CategoryId = 17,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ghế ăn, ghế bar",
                            DisplayOrder = 2,
                            ImageUrl = "/images/categories/ghe-an.jpg",
                            IsActive = true,
                            Name = "Ghế Ăn",
                            ParentId = 3,
                            Slug = "ghe-an"
                        },
                        new
                        {
                            CategoryId = 18,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tủ rượu, tủ bày đồ",
                            DisplayOrder = 3,
                            ImageUrl = "/images/categories/tu-ruou.jpg",
                            IsActive = true,
                            Name = "Tủ Rượu",
                            ParentId = 3,
                            Slug = "tu-ruou"
                        },
                        new
                        {
                            CategoryId = 19,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bàn văn phòng, bàn máy tính",
                            DisplayOrder = 1,
                            ImageUrl = "/images/categories/ban-lam-viec.jpg",
                            IsActive = true,
                            Name = "Bàn Làm Việc",
                            ParentId = 10,
                            Slug = "ban-lam-viec"
                        },
                        new
                        {
                            CategoryId = 20,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ghế xoay, ghế công thái học",
                            DisplayOrder = 2,
                            ImageUrl = "/images/categories/ghe-van-phong.jpg",
                            IsActive = true,
                            Name = "Ghế Văn Phòng",
                            ParentId = 10,
                            Slug = "ghe-van-phong"
                        },
                        new
                        {
                            CategoryId = 21,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tủ đựng tài liệu",
                            DisplayOrder = 3,
                            ImageUrl = "/images/categories/tu-ho-so.jpg",
                            IsActive = true,
                            Name = "Tủ Hồ Sơ",
                            ParentId = 10,
                            Slug = "tu-ho-so"
                        });
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Collection", b =>
                {
                    b.Property<int>("CollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollectionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CollectionId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Entities.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SelectedAttributes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Entities.OrderStatusHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("HistoryId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderStatusHistories");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Entities.ProductImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            ImageId = 1,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            ImageUrl = "/images/products/sofa-da-cao-cap-luxury.jpg",
                            IsPrimary = true,
                            ProductId = 1
                        },
                        new
                        {
                            ImageId = 2,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            ImageUrl = "/images/products/sofa-ni-scandinavian.jpg",
                            IsPrimary = true,
                            ProductId = 2
                        },
                        new
                        {
                            ImageId = 3,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            ImageUrl = "/images/products/ban-tra-go-oc-cho.jpg",
                            IsPrimary = true,
                            ProductId = 3
                        },
                        new
                        {
                            ImageId = 4,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            ImageUrl = "/images/products/giuong-ngu-nem-boc-vai.jpg",
                            IsPrimary = true,
                            ProductId = 4
                        },
                        new
                        {
                            ImageId = 5,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            ImageUrl = "/images/products/tu-quan-ao-4-canh.jpg",
                            IsPrimary = true,
                            ProductId = 5
                        });
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Entities.ProductVariant", b =>
                {
                    b.Property<int>("VariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VariantId"));

                    b.Property<decimal>("AdditionalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Size")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("VariantId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Entities.ProductView", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ProductViews_UserId_Filtered")
                        .HasFilter("[UserId] IS NOT NULL");

                    b.HasIndex("ViewedAt")
                        .HasDatabaseName("IX_ProductViews_ViewedAt");

                    b.HasIndex("ProductId", "ViewedAt")
                        .HasDatabaseName("IX_ProductViews_ProductId_ViewedAt");

                    b.ToTable("ProductViews");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("PurchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseOrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("POCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseOrderId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Entities.PurchaseOrderDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("DetailId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("VariantId");

                    b.ToTable("PurchaseOrderDetails");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Entities.ShoppingCart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ShippingCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingDistrict")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ShippingMethodId")
                        .HasColumnType("int");

                    b.Property<string>("ShippingPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShippingWard")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("ShippingMethodId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Orders_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Orders_UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<decimal>("AttributesAdjustment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ProductSKU")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SelectedAttributes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_OrderDetails_ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CollectionId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Depth")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SKU")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("BasePrice")
                        .HasDatabaseName("IX_Products_BasePrice");

                    b.HasIndex("CollectionId");

                    b.HasIndex("IsFeatured")
                        .HasDatabaseName("IX_Products_IsFeatured");

                    b.HasIndex("Material")
                        .HasDatabaseName("IX_Products_Material");

                    b.HasIndex("ProductType")
                        .HasDatabaseName("IX_Products_ProductType");

                    b.HasIndex("SKU");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("[Slug] IS NOT NULL");

                    b.HasIndex("CategoryId", "IsActive", "CreatedAt")
                        .HasDatabaseName("IX_Products_CategoryId_IsActive_CreatedAt");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            BasePrice = 25000000m,
                            Brand = "LuxuryHome",
                            CategoryId = 4,
                            Color = "Nâu đen",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Depth = 95m,
                            Description = "Sofa da bò thật nhập khẩu từ Ý, khung gỗ sồi chắc chắn.",
                            Height = 85m,
                            IsActive = true,
                            IsFeatured = true,
                            Material = "Da bò Ý",
                            Name = "Sofa Da Cao Cấp Luxury",
                            ProductType = "Sofa",
                            SKU = "SOFA-LUX-001",
                            Slug = "sofa-da-cao-cap-luxury",
                            StockQuantity = 10,
                            ViewCount = 0,
                            Weight = 85m,
                            Width = 220m
                        },
                        new
                        {
                            ProductId = 2,
                            BasePrice = 12000000m,
                            Brand = "ModernLife",
                            CategoryId = 4,
                            Color = "Xám nhạc",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Depth = 85m,
                            Description = "Sofa nỉ mềm mại, màu sắc trung tính phù hợp không gian hiện đại.",
                            Height = 80m,
                            IsActive = true,
                            IsFeatured = false,
                            Material = "Nỉ cao cấp",
                            Name = "Sofa Nỉ Phong Cách Scandinavian",
                            ProductType = "Sofa",
                            SKU = "SOFA-SCA-002",
                            Slug = "sofa-ni-scandinavian",
                            StockQuantity = 15,
                            ViewCount = 0,
                            Weight = 60m,
                            Width = 180m
                        },
                        new
                        {
                            ProductId = 3,
                            BasePrice = 8500000m,
                            Brand = "NatureWood",
                            CategoryId = 5,
                            Color = "Tự nhiên",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Depth = 60m,
                            Description = "Bàn trà làm từ gỗ óc chó tự nhiên, vân gỗ đẹp mắt.",
                            Height = 45m,
                            IsActive = true,
                            IsFeatured = true,
                            Material = "Gỗ óc chó",
                            Name = "Bàn Trà Gỗ Óc Chó",
                            ProductType = "Table",
                            SKU = "TABLE-WAL-003",
                            Slug = "ban-tra-go-oc-cho",
                            StockQuantity = 20,
                            ViewCount = 0,
                            Weight = 25m,
                            Width = 120m
                        },
                        new
                        {
                            ProductId = 4,
                            BasePrice = 18000000m,
                            Brand = "SleepWell",
                            CategoryId = 6,
                            Color = "Xanh navy",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Depth = 200m,
                            Description = "Giường ngủ êm ái với đầu giường bọc vải nhung sang trọng.",
                            Height = 110m,
                            IsActive = true,
                            IsFeatured = false,
                            Material = "Vải nhung, gỗ thông",
                            Name = "Giường Ngủ Nệm Bọc Vải",
                            ProductType = "Bed",
                            SKU = "BED-VEL-004",
                            Slug = "giuong-ngu-nem-boc-vai",
                            StockQuantity = 5,
                            ViewCount = 0,
                            Weight = 120m,
                            Width = 180m
                        },
                        new
                        {
                            ProductId = 5,
                            BasePrice = 15000000m,
                            Brand = "ModernLife",
                            CategoryId = 7,
                            Color = "Trắng",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Depth = 60m,
                            Description = "Tủ quần áo rộng rãi, thiết kế tối giản tích hợp gương soi.",
                            Height = 220m,
                            IsActive = true,
                            IsFeatured = false,
                            Material = "Gỗ công nghiệp MDF",
                            Name = "Tủ Quần Áo 4 Cánh Hiện Đại",
                            ProductType = "Wardrobe",
                            SKU = "WARD-MOD-005",
                            Slug = "tu-quan-ao-4-canh",
                            StockQuantity = 8,
                            ViewCount = 0,
                            Weight = 180m,
                            Width = 200m
                        });
                });

            modelBuilder.Entity("FurnitureShop.API.Models.ProductAttribute", b =>
                {
                    b.Property<int>("AttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttributeId"));

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AttributeValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("PriceAdjustment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("AttributeId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAttributes");

                    b.HasData(
                        new
                        {
                            AttributeId = 1,
                            AttributeName = "Bảo hành",
                            AttributeValue = "24 tháng",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            IsAvailable = true,
                            PriceAdjustment = 0m,
                            ProductId = 1
                        },
                        new
                        {
                            AttributeId = 2,
                            AttributeName = "Độ cứng",
                            AttributeValue = "Vừa phải",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            IsAvailable = true,
                            PriceAdjustment = 0m,
                            ProductId = 1
                        },
                        new
                        {
                            AttributeId = 3,
                            AttributeName = "Kích thước đệm",
                            AttributeValue = "1m8 x 2m",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            IsAvailable = true,
                            PriceAdjustment = 0m,
                            ProductId = 4
                        });
                });

            modelBuilder.Entity("FurnitureShop.API.Models.ShippingMethod", b =>
                {
                    b.Property<int>("ShippingMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShippingMethodId"));

                    b.Property<string>("ApplicableRegions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BaseFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedDeliveryDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("FeePerCubicMeter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FeePerKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FeePerKm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ShippingMethodId");

                    b.ToTable("ShippingMethods");

                    b.HasData(
                        new
                        {
                            ShippingMethodId = 1,
                            ApplicableRegions = "[\"TP.HCM\"]",
                            BaseFee = 50000m,
                            Code = "LOCAL",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giao hàng trong nội thành TP.HCM",
                            DisplayOrder = 0,
                            EstimatedDeliveryDays = 1,
                            FeePerCubicMeter = 100000m,
                            FeePerKg = 5000m,
                            IsActive = true,
                            Name = "Giao hàng nội thành"
                        },
                        new
                        {
                            ShippingMethodId = 2,
                            BaseFee = 100000m,
                            Code = "REGIONAL",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giao hàng các tỉnh miền Nam",
                            DisplayOrder = 0,
                            EstimatedDeliveryDays = 3,
                            FeePerCubicMeter = 150000m,
                            FeePerKg = 8000m,
                            IsActive = true,
                            Name = "Giao hàng liên tỉnh miền Nam"
                        },
                        new
                        {
                            ShippingMethodId = 3,
                            BaseFee = 150000m,
                            Code = "NATIONAL",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giao hàng toàn quốc",
                            DisplayOrder = 0,
                            EstimatedDeliveryDays = 5,
                            FeePerCubicMeter = 200000m,
                            FeePerKg = 10000m,
                            IsActive = true,
                            Name = "Giao hàng toàn quốc"
                        });
                });

            modelBuilder.Entity("FurnitureShop.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtpCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ward")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@furnitures.com",
                            FullName = "Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$Ify5IXQpdCwofnU29qjiuOVyWqe0/1GAl8teDWL05lV/jOCmLomuW",
                            Role = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Category", b =>
                {
                    b.HasOne("FurnitureShop.API.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Entities.CartItem", b =>
                {
                    b.HasOne("FurnitureShop.API.Models.Entities.ShoppingCart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FurnitureShop.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Entities.OrderStatusHistory", b =>
                {
                    b.HasOne("FurnitureShop.API.Models.Order", "Order")
                        .WithMany("StatusHistories")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Entities.ProductImage", b =>
                {
                    b.HasOne("FurnitureShop.API.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Entities.ProductVariant", b =>
                {
                    b.HasOne("FurnitureShop.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Entities.ProductView", b =>
                {
                    b.HasOne("FurnitureShop.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("FurnitureShop.API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FurnitureShop.API.Models.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Entities.PurchaseOrderDetail", b =>
                {
                    b.HasOne("FurnitureShop.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FurnitureShop.API.Models.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Details")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FurnitureShop.API.Models.Entities.ProductVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Entities.ShoppingCart", b =>
                {
                    b.HasOne("FurnitureShop.API.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("FurnitureShop.API.Models.Entities.ShoppingCart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Order", b =>
                {
                    b.HasOne("FurnitureShop.API.Models.ShippingMethod", "ShippingMethod")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingMethodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FurnitureShop.API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShippingMethod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.OrderDetail", b =>
                {
                    b.HasOne("FurnitureShop.API.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FurnitureShop.API.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Product", b =>
                {
                    b.HasOne("FurnitureShop.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FurnitureShop.API.Models.Collection", "Collection")
                        .WithMany("Products")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.ProductAttribute", b =>
                {
                    b.HasOne("FurnitureShop.API.Models.Product", "Product")
                        .WithMany("Attributes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Collection", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Entities.ShoppingCart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.Product", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Images");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.ShippingMethod", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FurnitureShop.API.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
